server:
  port: 80

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/product_show?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=true&serverTimezone=Asia/Shanghai


wx:
  mp:
    configs:
      - appId: 1111 （一个公众号的appid）
        secret: 1111（公众号的appsecret）
        token: 123hhiwhriw321
        aesKey: N2Hgry8ktoAzcVofRbYFZBZBas4HL9Uj9BrnlPPZuFk
#      - appId: 2222 （另一个公众号的appid，以下同上）
#        secret: 1111
#        token: 111
#        aesKey: 111